### ISSUE TITLE
cmd/geth: Change to default gcmode preventing lost blocks

### ISSUE THREAD

**Issue by sifnoc** [Onther-Tech/plasma-evm#123]
When Plasma-EVM process killed by accidently.

If not using `--gcmode "archive"` for running plasma-evm, you will see result like this when restart plasma-evm after process killed abnormally.
```
INFO [05-08|13:34:42.947] Commit new mining work                   number=6 sealhash=a5773d…36db3f uncles=0 txs=2 gas=42000 fees=4.2e-05 elapsed=1.139ms
INFO [05-08|13:34:42.947] Successfully sealed new block            number=6 sealhash=a5773d…36db3f hash=6d082b…870200 elapsed=427.697µs
INFO [05-08|13:34:42.948] 🔨 mined potential block                  number=6 hash=6d082b…870200
INFO [05-08|13:34:42.948] New block is mined                       number=6
INFO [05-08|13:34:42.948] IPC endpoint opened                      url=/Users/jinhwan/gitrepo/plasma-evm/.pls.staking/operator2/geth.ipc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49759d4]

goroutine 195 [running]:
github.com/Onther-Tech/plasma-evm/core/types.(*Block).Number(...)
        /Users/jinhwan/.gvm/pkgsets/go1.13/global/src/github.com/Onther-Tech/plasma-evm/core/types/block.go:312
github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).addEpochSubmitTransaction(0xc000828320, 0xc0000c6f00, 0x2, 0x2, 0xc00151fe38, 0x6)
        /Users/jinhwan/.gvm/pkgsets/go1.13/global/src/github.com/Onther-Tech/plasma-evm/pls/rootchain_manager.go:352 +0x274
github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).runSubmitter.func1(0xc000922240, 0x0, 0x0)
        /Users/jinhwan/.gvm/pkgsets/go1.13/global/src/github.com/Onther-Tech/plasma-evm/pls/rootchain_manager.go:451 +0x726
github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).runSubmitter(0xc000828320)
        /Users/jinhwan/.gvm/pkgsets/go1.13/global/src/github.com/Onther-Tech/plasma-evm/pls/rootchain_manager.go:474 +0x201
created by github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).run
        /Users/jinhwan/.gvm/pkgsets/go1.13/global/src/github.com/Onther-Tech/plasma-evm/pls/rootchain_manager.go:175 +0x65
```

currently, gcmode is "full" have to change gcmode to "archive".

**Comment by sifnoc** [comment]
Changed at 09be2658509bb9de60529d56fdad4f624692c38c
