### ISSUE TITLE
crashed in handleBlockFinalized

### ISSUE THREAD

**Issue by modagi** [Onther-Tech/plasma-evm#134]
#### System information

Geth version: 
````
Geth
Version: 1.9.1-stable
Git Commit: 4bf7d7e315e19a2b31683935e866ae952b32ab7d
Git Commit Date: 20200406
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.14
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.14
````
Plasma-evm version:
````
Version: 1.9.10-stable
Git Commit: 3fd45f8a7ad8f478c23ad1a0587e12ae2a824e99
Git Commit Date: 20200520
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.14
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.14
````
OS & Version: Ubuntu 18.04.1 LTS
Commit hash : 3fd45f8a7ad8f478c23ad1a0587e12ae2a824e99

#### Expected behaviour

shouldn't crash

#### Actual behaviour

crash

#### Steps to reproduce the behaviour

test test_requestable.py (https://github.com/Onther-Tech/tokamak-network-test)

#### Random test backtrace

````
opcode 2 : 0xaA60af9BD19dc7438fd19457955C52982D070D27, c9059de8e68f483f534ff2bbf9f230d09f9691699b7dbeb8b44257e511f4fb05, 0x00000000000000000000000000000000
opcode 4 : 0xC927A0CF2d4a1B59775B5D0A35ec76d099e1FaD4, 0x48aFf0622a866d77651eAaA462Ea77b5F39D0ae1, 992874217
opcode 0 : 0xec4A610a07e81264e8f7F1CAeAe522fEdD7e59c1, 891332370
opcode 1 : 0xb715125A08140AEA83588a4b569599cde4a0a336, 4c00cacaaf5ef155a8e67f0370e9fc524748551080083036991b1423b2f668db, 000000000000000000000000000000000000000000000000000000001ad72170
opcode 0 : 0x48aFf0622a866d77651eAaA462Ea77b5F39D0ae1, 924508723
opcode 4 : 0xb715125A08140AEA83588a4b569599cde4a0a336, 0xC927A0CF2d4a1B59775B5D0A35ec76d099e1FaD4, 472025900
opcode 3 : 0xaA60af9BD19dc7438fd19457955C52982D070D27, 0x515B385bDc89bCc29077f2B00a88622883bfb498
opcode 4 : 0xb715125A08140AEA83588a4b569599cde4a0a336, 0xec4A610a07e81264e8f7F1CAeAe522fEdD7e59c1, 55656962
opcode 2 : 0x515B385bDc89bCc29077f2B00a88622883bfb498, 9c4df1d8478abc345d9ede2e4386c63af1336152194130e8f1d04f672f99b25f, 0x00000000000000000000000000000000
opcode 1 : 0xb715125A08140AEA83588a4b569599cde4a0a336, 4c00cacaaf5ef155a8e67f0370e9fc524748551080083036991b1423b2f668db, 0000000000000000000000000000000000000000000000000000000000c87d35
opcode 0 : 0xC927A0CF2d4a1B59775B5D0A35ec76d099e1FaD4, 658837980
opcode 4 : 0xC927A0CF2d4a1B59775B5D0A35ec76d099e1FaD4, 0xb715125A08140AEA83588a4b569599cde4a0a336, 34540094
opcode 1 : 0x515B385bDc89bCc29077f2B00a88622883bfb498, 9c4df1d8478abc345d9ede2e4386c63af1336152194130e8f1d04f672f99b25f, 0000000000000000000000000000000000000000000000000000000010337d3c
opcode 3 : 0x515B385bDc89bCc29077f2B00a88622883bfb498, 0x48aFf0622a866d77651eAaA462Ea77b5F39D0ae1
opcode 1 : 0xec4A610a07e81264e8f7F1CAeAe522fEdD7e59c1, bd160060985bbbe5f53447c152178512818b28eca9204127c957b64863a68e2e, 000000000000000000000000000000000000000000000000000000002d1b9f70
opcode 0 : 0x499De281cd965781F1422b7cB73367C15DC416D2, 129546203
opcode 2 : 0x37da08b6Cd15c3aE905A25Df57B6841A5D80aC93, 0e142ce7154cbeb747506ea79357c7a76808498eefa4437168728cbf2aaf01fb, 0x00000000000000000000000000000000
opcode 3 : 0x5E3230019fEd7aB462e3AC277E7709B9b2716b4F, 0xec4A610a07e81264e8f7F1CAeAe522fEdD7e59c1
opcode 3 : 0xC927A0CF2d4a1B59775B5D0A35ec76d099e1FaD4, 0xaA60af9BD19dc7438fd19457955C52982D070D27
opcode 3 : 0x515B385bDc89bCc29077f2B00a88622883bfb498, 0xec4A610a07e81264e8f7F1CAeAe522fEdD7e59c1
opcode 3 : 0x5E3230019fEd7aB462e3AC277E7709B9b2716b4F, 0x48aFf0622a866d77651eAaA462Ea77b5F39D0ae1
opcode 1 : 0xaA60af9BD19dc7438fd19457955C52982D070D27, c9059de8e68f483f534ff2bbf9f230d09f9691699b7dbeb8b44257e511f4fb05, 000000000000000000000000000000000000000000000000000000002ce22498
````

#### geth backtrace

````
goroutine 87 [running]:
github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).handleBlockFinalized(0xc000540b40, 0xc001c58780,      0x0, 0x0)
    /home/modagi/github/onther/plasma-evm/pls/rootchain_manager.go:727 +0xb25
github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).runHandlers(0xc000540b40)
    /home/modagi/github/onther/plasma-evm/pls/rootchain_manager.go:501 +0x15f
created by github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).run
    /home/modagi/github/onther/plasma-evm/pls/rootchain_manager.go:174 +0x43

````

**Comment by ggs134** [comment]
Where is test_requestable.py code?

**Comment by modagi** [comment]
> Where is test_requestable.py code?

https://github.com/Onther-Tech/tokamak-network-test

I edited above

**Comment by modagi** [comment]
fixed
