### ISSUE TITLE
Request Block invalid at User node

### ISSUE THREAD

**Issue by sifnoc** [Onther-Tech/plasma-evm#71]
Plasma-evm Operator Node does not matter generate ORB and insert into Chain, itself.
But, User node could not accept The ORB block from Operator node.

#### System information

Geth version: `geth.1.8.20-plasma-evm`
OS & Version: OSX/Ubuntu
Commit hash : develop commit 94d013d02512c1c795845e262cb86c5741895b87

#### Expected behaviour

User Node Accept *RB blocks as like NRB
```Bash
INFO [06-26|23:37:25.466] Watching epoch prepared event            start block number=0
INFO [06-26|23:37:25.466] Watching block finalized event           start block number=0
INFO [06-26|23:37:25.467] IPC endpoint opened                      url=/Users/jins/plasma-rbg/newgeth/geth.ipc
INFO [06-26|23:37:25.468] HTTP endpoint opened                     url=http://0.0.0.0:8547                     cors=* vhosts=172.30.1.20,172.30.1.39,localhost
INFO [06-26|23:37:45.358] Block synchronisation started
INFO [06-26|23:37:45.396] Imported new chain segment               blocks=2 txs=2 mgas=1.469 elapsed=2.374ms    mgasps=618.589 number=2 hash=39cdeb…2d5465 age=1d7h35m  cache=8.11kB
INFO [06-26|23:37:45.463] Imported new chain segment               blocks=46 txs=63 mgas=37.869 elapsed=59.359ms   mgasps=637.953 number=48 hash=4de322…8f3f85 age=1d4h28m  cache=244.67kB
```

#### Actual behaviour

User node block synchronisation failed

#### Steps to reproduce the behaviour

1. Setup Operator Node, User Node then Check Peer connection each other.
2. Use `startEnter` method at rootchain contract to make ORB on Operator Node.
3. Send some dummy transaction to make starting Mining ORB in Plasma-evm
4. Operator Node Generated ORB, User Node is going to sync These blocks.

#### Backtrace

````Bash
[backtrace]
INFO [06-25|11:51:37.681] Stats daemon started
INFO [06-25|11:51:37.687] IPC endpoint opened                      url=/root/.ethereum/geth.ipc
WARN [06-25|11:51:37.687] Stats server unreachable                 err="websocket.Dial ws://172.30.1.11/api: bad status"
INFO [06-25|11:51:37.688] HTTP endpoint opened                     url=http://0.0.0.0:8547      cors=* vhosts=172.30.1.11,172.30.1.39,localhost
INFO [06-25|11:51:47.547] Block synchronisation started
ERROR[06-25|11:51:47.571]
########## BAD BLOCK #########
Chain config: {ChainID: 16 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil> Engine: ethash}

Number: 49
Hash: 0x938796b8895d266d98e5c8eda602c29369f42690b8d6fd5095abf03a25f6d634
	 0: cumulative: 50150 gas: 50150 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x3556576fca4b70c699c457e2dda1f5a711df954f80ebe9d8209a6cca6a8e3d8e logs: [0xc0030f11e0] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000040000000000040000000000000000 state:
	 1: cumulative: 85364 gas: 35214 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x454a9d5b28bc9585907e78d6115a98cc6f5cb414128b2dce56ea14f6256f8140 logs: [0xc0030f1290] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000040000000000040000000000000000 state:


Error: invalid merkle root (remote: a7aab665128eccde77e9233c4cb3aa2c8d22751a8aa717455d9b6ba5cd072b04 local: ffe96e69a22e68c5aad96192407b83f5230805d7694fab62b6a29ced3f9dddc9)
##############################
````

**Comment by sifnoc** [comment]
https://github.com/Onther-Tech/plasma-evm/blob/develop/core/block_validator.go#L80-L101

Modified`ValidateState` function always return nil, to avoid block Validation, Temporary.

```go
func (v *BlockValidator) ValidateState(block, parent *types.Block, statedb *state.StateDB, receipts types.Receipts, usedGas uint64) error {
	return nil
	header := block.Header()
	if block.GasUsed() != usedGas {
		return fmt.Errorf("invalid gas used (remote: %d local: %d)", block.GasUsed(), usedGas)
	}
```

But, Still occured these error,
[backtrace]
```bash
INFO [06-26|23:37:25.466] Watching epoch prepared event            start block number=0
INFO [06-26|23:37:25.466] Watching block finalized event           start block number=0
INFO [06-26|23:37:25.467] IPC endpoint opened                      url=/Users/jins/plasma-rbg/newgeth/geth.ipc
INFO [06-26|23:37:25.468] HTTP endpoint opened                     url=http://0.0.0.0:8547                     cors=* vhosts=172.30.1.20,172.30.1.39,localhost
INFO [06-26|23:37:45.358] Block synchronisation started
INFO [06-26|23:37:45.396] Imported new chain segment               blocks=2 txs=2 mgas=1.469 elapsed=2.374ms    mgasps=618.589 number=2 hash=39cdeb…2d5465 age=1d7h35m  cache=8.11kB
INFO [06-26|23:37:45.463] Imported new chain segment               blocks=46 txs=63 mgas=37.869 elapsed=59.359ms   mgasps=637.953 number=48 hash=4de322…8f3f85 age=1d4h28m  cache=244.67kB
WARN [06-26|23:37:48.402] Synchronisation failed, dropping peer    peer=b485ed7460ad4d53 err="retrieved hash chain is invalid"
ERROR[06-26|23:37:48.402] Failed to reset txpool state             err="missing trie node a7aab665128eccde77e9233c4cb3aa2c8d22751a8aa717455d9b6ba5cd072b04 (path )"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4105f8e]

goroutine 828 [running]:
math/big.(*Int).Cmp(0xc004352720, 0x0, 0x93c202a6edc8e598)
	/usr/local/Cellar/go/1.11.4/libexec/src/math/big/int.go:319 +0x2e
github.com/Onther-Tech/plasma-evm/core.(*BlockChain).insertSidechain(0xc000355000, 0xc00458b6e0, 0xc00007b910, 0xc00007b901, 0x1, 0x1, 0xc000268520, 0x1, 0x1, 0xc0000c0420, ...)
	/Users/jins/plasma-rbg/build/_workspace/src/github.com/Onther-Tech/plasma-evm/core/blockchain.go:1375 +0x10b2
github.com/Onther-Tech/plasma-evm/core.(*BlockChain).insertChain(0xc000355000, 0xc0002dc090, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jins/plasma-rbg/build/_workspace/src/github.com/Onther-Tech/plasma-evm/core/blockchain.go:1181 +0x2e1e
github.com/Onther-Tech/plasma-evm/core.(*BlockChain).InsertChain(0xc000355000, 0xc0002dc090, 0x1, 0x1, 0x5b85f28, 0x0, 0x0)
	/Users/jins/plasma-rbg/build/_workspace/src/github.com/Onther-Tech/plasma-evm/core/blockchain.go:1130 +0xb89
github.com/Onther-Tech/plasma-evm/pls/downloader.(*Downloader).importBlockResults(0xc000348000, 0xc0002dc088, 0x1, 0x1, 0x1, 0x45fe7c8)
	/Users/jins/plasma-rbg/build/_workspace/src/github.com/Onther-Tech/plasma-evm/pls/downloader/downloader.go:1490 +0x40e
github.com/Onther-Tech/plasma-evm/pls/downloader.(*Downloader).processFullSyncContent(0xc000348000, 0x108, 0xc002b5f798)
	/Users/jins/plasma-rbg/build/_workspace/src/github.com/Onther-Tech/plasma-evm/pls/downloader/downloader.go:1464 +0x79
github.com/Onther-Tech/plasma-evm/pls/downloader.(*Downloader).processFullSyncContent-fm(0x8, 0x4e59a00)
	/Users/jins/plasma-rbg/build/_workspace/src/github.com/Onther-Tech/plasma-evm/pls/downloader/downloader.go:479 +0x2a
github.com/Onther-Tech/plasma-evm/pls/downloader.(*Downloader).spawnSync.func1(0xc000348000, 0xc004496cc0, 0xc002c3d6a0)
	/Users/jins/plasma-rbg/build/_workspace/src/github.com/Onther-Tech/plasma-evm/pls/downloader/downloader.go:491 +0x59
created by github.com/Onther-Tech/plasma-evm/pls/downloader.(*Downloader).spawnSync
	/Users/jins/plasma-rbg/build/_workspace/src/github.com/Onther-Tech/plasma-evm/pls/downloader/downloader.go:491 +0xaf
```

**Comment by sifnoc** [comment]
Tried to ignore L99, even not same between User Node calculate

https://github.com/Onther-Tech/plasma-evm/blob/803dad2c8cd71f0a64d97303fd82430b2cddb411/core/block_validator.go#L98-L100

**Comment by sifnoc** [comment]
Well Synced Block No.49 ORB

```
> web3.eth.getBlock(49)
{
  difficulty: 1,
  extraData: "0xd883010900846765746888676f312e31322e36856c696e7578",
  gasLimit: 953253062,
  gasUsed: 85364,
  hash: "0x92fc10b793c736dc735ac9d9bf609eedf1a5854cb09bc9e1e4ec81ce4af35da9",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000040000000000040000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 49,
  parentHash: "0xf6602f34522174b70a92183ef0f80b0c4afbbe466c409de028d108cfcfe6812f",
  receiptsRoot: "0x7bc3a49501e10b45c5ded27f2170216ae8682adec5a48c2fbcfd510ea25bd7d8",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 1075,
  stateRoot: "0x076c7ae402d40f859ea0dd12058969c4cdd009bf279f6d558482a2801e14f8de",
  timestamp: 1562643674,
  totalDifficulty: 3.40282366920938463463374607431768211505e+38,
  transactions: ["0x3556576fca4b70c699c457e2dda1f5a711df954f80ebe9d8209a6cca6a8e3d8e", "0x454a9d5b28bc9585907e78d6115a98cc6f5cb414128b2dce56ea14f6256f8140"],
  transactionsRoot: "0xac512ec81dc85fc07966c81961ed39a52cb4d50d43d861d55eb012c1e01e1b5c",
  uncles: []
}
```
